import { BudgetDialog } from "@/components/BudgetDialog";
import { useFinanceWorkspace } from "@/hooks/useFinanceWorkspace";
import { calculateBudgetHealth, formatInrFromPaise, getMonthKey } from "@shared/finance";
import { trpc } from "@/lib/trpc";
import { BudgetRing } from "@/components/BudgetRing";
import { AlertTriangle, Plus } from "lucide-react";
import { useMemo, useState } from "react";

export default function BudgetsPage() {
  const { activeSpace, activeSpaceId, categories, isLoading } = useFinanceWorkspace(); const [open, setOpen] = useState(false); const [initial, setInitial] = useState<any>(null); const monthKey = useMemo(() => getMonthKey(new Date()), []);
  const budgets = trpc.finance.budgets.list.useQuery({ spaceId: activeSpaceId ?? 0, monthKey }, { enabled: !!activeSpaceId });
  if (isLoading || !activeSpace) return <WorkspaceSkeleton />;
  const totalBudget = budgets.data?.reduce((sum, item) => sum + item.amountPaise, 0) ?? 0; const totalSpend = budgets.data?.reduce((sum, item) => sum + item.spentPaise, 0) ?? 0; const overall = calculateBudgetHealth(totalSpend, totalBudget);
  const canManage = activeSpace.role === "owner";
  return <div className="workspace-page"><header className="workspace-head"><div><p className="workspace-kicker">{new Intl.DateTimeFormat("en-IN", { month: "long", year: "numeric" }).format(new Date())}</p><h1>Budgets that breathe.</h1><p className="workspace-subtitle">Set a useful line, then let the pattern—not pressure—guide your next move.</p></div>{canManage && <button className="workspace-add" type="button" onClick={() => { setInitial(null); setOpen(true); }}><Plus size={17} /> Set budget</button>}</header><section className="budget-hero"><div><p>Monthly budget posture</p><strong>{totalBudget ? `${overall.percent}%` : "—"}</strong><span>{totalBudget ? `${formatInrFromPaise(totalSpend)} of ${formatInrFromPaise(totalBudget)} allocated` : "No category budgets have been set yet."}</span></div><BudgetRing className="budget-ring" percent={overall.percent} label={overall.state === "over" ? "Over" : overall.state === "watch" ? "Watch" : overall.state === "healthy" ? "Steady" : "Ready"} /></section>{overall.state === "over" || overall.state === "watch" ? <div className={`budget-alert budget-alert--${overall.state}`}><AlertTriangle size={16} />{overall.state === "over" ? "The combined budget has been exceeded. Open category rings to see where the pressure sits." : "The combined budget is nearing its boundary. A quick look now can prevent a surprise later."}</div> : null}<section className="budget-grid">{budgets.data?.length ? budgets.data.map(item => { const health = calculateBudgetHealth(item.spentPaise, item.amountPaise); return <article key={item.id} className="budget-card"><div className="budget-card__top"><span className={`category-dot category-dot--${item.categoryColor}`} /><h2>{item.categoryName}</h2>{canManage && <button type="button" onClick={() => { setInitial(item); setOpen(true); }}>Adjust</button>}</div><div className="budget-card__body"><BudgetRing className={`budget-card__ring budget-card__ring--${health.state}`} percent={health.percent} label={`${health.percent}%`} /><p>{formatInrFromPaise(item.spentPaise)} <span>of {formatInrFromPaise(item.amountPaise)}</span><small className={health.state === "over" || health.state === "watch" ? "budget-warning" : ""}>{(health.state === "over" || health.state === "watch") && <AlertTriangle size={13} />}{health.state === "over" ? "Over budget" : health.state === "watch" ? "Near budget boundary" : `Alert at ${item.alertAtPercent}%`}</small></p></div></article>; }) : <div className="empty-state budget-empty"><h2>Budgets work best when they start small.</h2><p>Choose one category that is useful to keep an eye on. You can change the boundary any time.</p>{canManage && <button className="workspace-add" type="button" onClick={() => setOpen(true)}><Plus size={16} /> Set first budget</button>}</div>}</section><BudgetDialog open={open} onOpenChange={setOpen} spaceId={activeSpace.id} monthKey={monthKey} categories={categories} initial={initial} /></div>;
}
function WorkspaceSkeleton() { return <div className="workspace-page"><div className="skeleton h-9 w-64" /><div className="skeleton mt-7 h-48" /></div>; }
