import { TransactionDialog } from "@/components/TransactionDialog";
import { useFinanceWorkspace } from "@/hooks/useFinanceWorkspace";
import { formatInrFromPaise, getMonthKey } from "@shared/finance";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Flame, Plus, Sparkles, TrendingDown, TrendingUp, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";

export default function DashboardPage() {
  const { activeSpace, activeSpaceId, setActiveSpaceId, spaces, categories, isLoading } = useFinanceWorkspace();
  const [dialogOpen, setDialogOpen] = useState(false); const [, navigate] = useLocation();
  const monthKey = useMemo(() => getMonthKey(new Date()), []);
  const dashboard = trpc.finance.dashboard.get.useQuery({ spaceId: activeSpaceId ?? 0, monthKey }, { enabled: !!activeSpaceId });
  if (isLoading || !activeSpace) return <WorkspaceSkeleton />;
  const data = dashboard.data; const topCategory = data?.categorySpend[0];
  return <div className="workspace-page"><header className="workspace-head"><div><p className="workspace-kicker">{new Intl.DateTimeFormat("en-IN", { month: "long", year: "numeric" }).format(new Date())}</p><h1>Good to see you.</h1><p className="workspace-subtitle">Your money, in the context of <strong>{activeSpace.name}</strong>.</p></div><div className="workspace-head__actions"><select aria-label="Active Expense Space" className="space-switcher" value={activeSpaceId ?? ""} onChange={event => setActiveSpaceId(Number(event.target.value))}>{spaces.map(space => <option value={space.id} key={space.id}>{space.name} · {space.role}</option>)}</select><button className="workspace-add" type="button" onClick={() => setDialogOpen(true)}><Plus size={17} /> Add entry</button></div></header>
    <section className="summary-grid" aria-label="Monthly summary"><article className="summary-card summary-card--primary"><p>Current balance</p><strong>{formatInrFromPaise(data?.summary.balancePaise ?? 0)}</strong><span><WalletCards size={14} /> Across this space</span></article><article className="summary-card"><p>In this month</p><strong>{formatInrFromPaise(data?.summary.incomePaise ?? 0)}</strong><span className="positive"><TrendingUp size={14} /> Income logged</span></article><article className="summary-card"><p>Out this month</p><strong>{formatInrFromPaise(data?.summary.expensePaise ?? 0)}</strong><span className="negative"><TrendingDown size={14} /> Spending logged</span></article></section>
    <section className="dashboard-grid" aria-label="Financial insight and logging streak"><article className="workspace-card workspace-card--insight"><div className="card-label"><Sparkles size={15} /> Arthra observation</div>{data?.recentTransactions.length ? <><h2>{topCategory ? `${topCategory.name} has your attention this month.` : "You are building a useful picture."}</h2><p>{topCategory ? `${formatInrFromPaise(topCategory.amountPaise)} is currently grouped here. Explore the trend when you want the detail.` : "Every entry adds a little more context. Your first useful pattern will appear after a few logs."}</p><button type="button" onClick={() => navigate("/analytics")}>See the trend <ArrowRight size={15} /></button></> : <><h2>Start with one small record.</h2><p>A few seconds now becomes a more useful picture of your month later.</p><button type="button" onClick={() => setDialogOpen(true)}>Add the first entry <ArrowRight size={15} /></button></>}</article><article className="workspace-card workspace-card--streak" aria-label="Logging streak"><div className="streak-orb"><Flame size={30} /></div><p className="card-label">Logging streak</p><strong>{data?.streak.currentStreak ?? 0} day{(data?.streak.currentStreak ?? 0) === 1 ? "" : "s"}</strong><span>{(data?.streak.currentStreak ?? 0) ? "A small habit with a long memory." : "Your first log starts the spark."}</span></article></section>
    <section className="workspace-card activity-card" aria-labelledby="recent-entries-heading"><div className="section-title-row"><div><p className="workspace-kicker">Latest movement</p><h2 id="recent-entries-heading">Recent entries</h2></div><button type="button" className="quiet-action" onClick={() => navigate("/transactions")}>All transactions <ArrowRight size={15} /></button></div>{data?.recentTransactions.length ? <div className="transaction-list" aria-label="Recent transactions">{data.recentTransactions.map(item => <button type="button" className="transaction-row" key={item.id} onClick={() => navigate("/transactions")}><span className={`transaction-icon ${item.kind === "income" ? "is-income" : ""}`}>{item.description.slice(0, 1).toUpperCase()}</span><span className="transaction-row__text"><strong>{item.description}</strong><small>{item.categoryName ?? "Uncategorised"} · {new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short" }).format(item.occurredAt)}</small></span><strong className={item.kind === "income" ? "amount-positive" : "amount-negative"}>{item.kind === "income" ? "+" : "−"}{formatInrFromPaise(item.amountPaise)}</strong></button>)}</div> : <div className="empty-state"><span className="empty-state__glyph">₹</span><p>No entries yet. Your private workspace is ready when you are.</p></div>}</section>
    <TransactionDialog open={dialogOpen} onOpenChange={setDialogOpen} spaceId={activeSpace.id} categories={categories} />
  </div>;
}
function WorkspaceSkeleton() { return <div className="workspace-page"><div className="skeleton h-8 w-60" /><div className="summary-grid mt-8"><div className="skeleton h-36" /><div className="skeleton h-36" /><div className="skeleton h-36" /></div><div className="skeleton mt-5 h-72" /></div>; }
