import { BrandMark } from "@/components/BrandMark";
import { demoBudgets, demoInsights, demoMonthlyTrend, demoSpaces, demoTransactions } from "@/demo/demoData";
import { formatInrFromPaise } from "@shared/finance";
import { ArrowRight, BarChart3, BrainCircuit, CheckCircle2, FileOutput, ReceiptText, ShieldCheck, UsersRound, WalletCards, X } from "lucide-react";

const money = (amountPaise: number) => formatInrFromPaise(amountPaise, 0);
const totalExpenses = demoTransactions.filter(item => item.kind === "expense").reduce((sum, item) => sum + item.amountPaise, 0);

function DemoSectionHeading({ eyebrow, title, copy, icon: Icon }: { eyebrow: string; title: string; copy: string; icon: typeof BarChart3 }) {
  return <header className="demo-section-head"><div><p className="demo-eyebrow">{eyebrow}</p><h2>{title}</h2><p>{copy}</p></div><span className="demo-section-icon"><Icon size={20} /></span></header>;
}

export default function DemoPage() {
  return <main className="demo-site">
    <header className="demo-topbar"><a href="/" aria-label="Exit Arthra demo and return to home"><BrandMark /></a><nav aria-label="Demo navigation"><a href="#dashboard">Dashboard</a><a href="#transactions">Transactions</a><a href="#budgets">Budgets</a><a href="#insights">Insights</a><a href="#spaces">Spaces</a><a href="#reports">Reports</a></nav><a className="demo-exit" href="/"><X size={15} /> Exit demo</a></header>

    <section className="demo-hero" aria-labelledby="demo-title"><div><span className="demo-badge">DEMO DATA</span><p className="demo-eyebrow">A safe product walkthrough</p><h1 id="demo-title">Explore Arthra in two minutes.</h1><p>These fictional examples live only in this read-only demo. They never write to, merge with, or reveal a real financial workspace.</p><div className="demo-hero-actions"><a href="#dashboard" className="demo-primary">Start the walkthrough <ArrowRight size={16} /></a><a href="/" className="demo-secondary">Create a private workspace</a></div></div><aside className="demo-hero-card"><p>August 2026</p><strong>{money(75_000_00)}</strong><span>Fictional monthly income</span><div><i /><i /><i /><i /><i /><i /></div></aside></section>

    <section id="dashboard" className="demo-section" aria-labelledby="demo-dashboard-title"><DemoSectionHeading eyebrow="01 · Dashboard" title="A calm overview with useful signals" copy="Every figure below is fictional and shown only to demonstrate the product structure." icon={WalletCards} /><div className="demo-stat-grid"><article className="demo-stat demo-stat--primary"><span>Monthly income</span><strong>{money(75_000_00)}</strong><small><CheckCircle2 size={13} /> Fictional salary credit</small></article><article className="demo-stat"><span>Total expenses</span><strong>{money(totalExpenses)}</strong><small>Across 9 fictional expenses</small></article><article className="demo-stat"><span>Potential savings</span><strong>{money(32_887_00)}</strong><small>Income less demo expenses</small></article><article className="demo-stat"><span>Budget posture</span><strong>4 on track</strong><small>1 near limit · 1 over</small></article></div><article className="demo-observation"><BrainCircuit size={20} /><div><p className="demo-eyebrow">Calculated insight</p><h3>Entertainment needs a small review.</h3><p>The example subscription and entertainment total is above its fictional monthly limit. Arthra describes the record context; it does not tell a person what to buy, sell, or invest in.</p></div></article></section>

    <section id="transactions" className="demo-section demo-section--split" aria-labelledby="demo-transactions-title"><div><DemoSectionHeading eyebrow="02 · Transactions" title="A ledger that keeps context close" copy="Income, recurring bills, GST notes, receipts, categories, and filters remain in the real workspace. This is a read-only sample." icon={ReceiptText} /><div className="demo-table" role="region" aria-label="Fictional demo transactions"><div className="demo-table__head"><span>Date</span><span>Record</span><span>Category</span><span>Amount</span></div>{demoTransactions.slice(0, 7).map(item => <div className="demo-table__row" key={item.id}><span>{item.date}</span><strong>{item.description}</strong><span>{item.category}</span><b className={item.kind === "income" ? "is-income" : ""}>{item.kind === "income" ? "+" : "−"}{money(item.amountPaise)}</b></div>)}</div></div><aside className="demo-callout"><ReceiptText size={20} /><h3>Receipt-assisted entry</h3><p>In a real workspace, image receipt suggestions are always reviewable. The user can edit every proposed field before saving; PDFs continue through the existing attachment flow.</p><span>Never auto-saves a transaction</span></aside></section>

    <section id="budgets" className="demo-section" aria-labelledby="demo-budgets-title"><DemoSectionHeading eyebrow="03 · Budgets" title="Boundaries that are easy to read" copy="Text, labels, and ring progress explain each budget state instead of relying on color alone." icon={WalletCards} /><div className="demo-budget-grid">{demoBudgets.map(item => { const percent = Math.min(100, Math.round((item.spentPaise / item.budgetPaise) * 100)); const status = item.state === "over" ? "Over budget" : item.state === "near" ? "Near limit" : "On track"; return <article className={`demo-budget demo-budget--${item.state}`} key={item.name}><div className="demo-budget__top"><h3>{item.name}</h3><span>{status}</span></div><strong>{money(item.spentPaise)}</strong><p>of {money(item.budgetPaise)} planned</p><div className="demo-progress" aria-label={`${item.name} is ${percent}% used`}><i style={{ width: `${percent}%` }} /></div><small>{percent}% used</small></article>; })}</div></section>

    <section id="insights" className="demo-section demo-section--insights" aria-labelledby="demo-insights-title"><DemoSectionHeading eyebrow="04 · Analytics and AI financial insights" title="Useful intelligence, clearly labelled" copy="Arthra separates calculated observations from optional AI summaries and shows an empty state when history is not sufficient." icon={BarChart3} /><div className="demo-analytics-grid"><article className="demo-chart"><h3>Six-month rhythm</h3><div className="demo-bars" aria-label="Fictional six-month expense trend">{demoMonthlyTrend.map(point => <div key={point.month}><i style={{ height: `${Math.round(point.expensePaise / 60000)}%` }} /><span>{point.month}</span></div>)}</div><p>Spending is shown against fictional income history.</p></article><div className="demo-insight-stack">{demoInsights.map(item => <article className="demo-insight" key={item.title}><span>{item.label}</span><h3>{item.title}</h3><p>{item.description}</p><button type="button" disabled>View detailed analysis <ArrowRight size={14} /></button></article>)}</div></div></section>

    <section id="spaces" className="demo-section demo-section--split" aria-labelledby="demo-spaces-title"><div><DemoSectionHeading eyebrow="05 · Expense Spaces" title="Share only the context that belongs together" copy="The real app enforces Owner, Editor, and Viewer permissions on the server. This read-only demo illustrates the experience." icon={UsersRound} /><div className="demo-space-grid">{demoSpaces.map(space => <article className="demo-space" key={space.name}><p>{space.role}</p><h3>{space.name}</h3><span>{space.description}</span><div>{space.members.map(member => <i key={member}>{member.slice(0, 1)}</i>)}</div></article>)}</div></div><aside className="demo-callout demo-callout--privacy"><ShieldCheck size={20} /><h3>Scoped, not social</h3><p>Members see only an Expense Space they belong to. Public pages never receive a person’s live transactions, receipts, budgets, or reports.</p><span>Owner · Editor · Viewer</span></aside></section>

    <section id="reports" className="demo-section" aria-labelledby="demo-reports-title"><DemoSectionHeading eyebrow="06 · Reports" title="Indian financial-year records, ready to hand off" copy="A read-only report can be shared for a limited time and revoked by the owner. This example does not create a real link." icon={FileOutput} /><article className="demo-report"><div><p className="demo-eyebrow">FY 2026–27 · Fictional ledger</p><h3>CA-ready demo handoff</h3><p>GST-aware entries, Apr–Mar financial years, and clear CSV export keep the reporting workflow grounded in Indian context.</p></div><div className="demo-report__actions"><button type="button" disabled>Export sample CSV</button><button type="button" disabled>Preview read-only link</button></div></article></section>

    <footer className="demo-footer"><div><span className="demo-badge">DEMO DATA</span><p>This experience is static, isolated, and read-only.</p></div><a className="demo-primary" href="/">Exit demo <ArrowRight size={16} /></a></footer>
  </main>;
}
