import { trpc } from "@/lib/trpc";
import { Inbox, Loader2, MailCheck, ShieldAlert, Trash2, UsersRound } from "lucide-react";

const contactStatuses = ["new", "in_progress", "resolved", "archived"] as const;
const waitlistStatuses = ["new", "reviewed", "archived"] as const;

function formatDate(value: Date | string) {
  return new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
}

export default function OperationsPage() {
  const utils = trpc.useUtils();
  const access = trpc.publicEngagement.operationsAccess.useQuery();
  const inbox = trpc.publicEngagement.operationsInbox.useQuery(undefined, { enabled: access.data?.canManage === true });
  const refresh = () => utils.publicEngagement.operationsInbox.invalidate();
  const setContactStatus = trpc.publicEngagement.setContactStatus.useMutation({ onSuccess: refresh });
  const setWaitlistStatus = trpc.publicEngagement.setWaitlistStatus.useMutation({ onSuccess: refresh });
  const deleteContact = trpc.publicEngagement.deleteContactRecord.useMutation({ onSuccess: refresh });
  const deleteWaitlist = trpc.publicEngagement.deleteWaitlistRecord.useMutation({ onSuccess: refresh });

  if (access.isLoading) return <div className="grid min-h-[50vh] place-items-center"><Loader2 className="size-6 animate-spin text-primary" aria-label="Checking owner access" /></div>;
  if (!access.data?.canManage) return <section className="mx-auto grid min-h-[56vh] max-w-2xl place-items-center text-center"><div className="rounded-3xl border border-border bg-card p-8 shadow-sm"><ShieldAlert className="mx-auto size-8 text-primary" /><p className="mt-5 text-xs font-bold uppercase tracking-[.16em] text-primary">Private area</p><h1 className="mt-3 text-3xl font-bold tracking-tight">Owner operations only.</h1><p className="mt-3 max-w-lg text-sm leading-6 text-muted-foreground">Contact messages and waitlist records remain private. This route never shows them to regular workspace members.</p></div></section>;

  const pending = setContactStatus.isPending || setWaitlistStatus.isPending || deleteContact.isPending || deleteWaitlist.isPending;
  return <section className="mx-auto max-w-6xl space-y-6 pb-20">
    <header className="rounded-3xl border border-primary/20 bg-card p-6 shadow-sm md:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Owner operations</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Private support inbox</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Review consented contact and waitlist records, record their handling state, and permanently delete a record when its purpose is complete or a deletion request is verified.</p></div><div className="rounded-2xl border border-border bg-background px-4 py-3 text-sm"><strong className="block">Operational rule</strong><span className="mt-1 block text-muted-foreground">Only collect, retain, and use records for the consented purpose.</span></div></div></header>

    {inbox.isLoading ? <div className="grid min-h-48 place-items-center rounded-3xl border border-border bg-card"><Loader2 className="size-6 animate-spin text-primary" aria-label="Loading private records" /></div> : inbox.isError ? <div className="rounded-3xl border border-destructive/30 bg-destructive/5 p-6 text-sm"><strong>Private records could not be loaded.</strong><p className="mt-2 text-muted-foreground">No data was exposed. Check the connection and try again.</p></div> : <>
      <section className="rounded-3xl border border-border bg-card p-5 md:p-6" aria-labelledby="contact-inbox-title"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Consent to reply</p><h2 id="contact-inbox-title" className="mt-1 text-xl font-bold">Contact messages</h2></div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary">{inbox.data?.messages.length ?? 0} private record{inbox.data?.messages.length === 1 ? "" : "s"}</span></div>
        <div className="mt-5 space-y-3">{inbox.data?.messages.length ? inbox.data.messages.map(item => <article key={item.id} className="rounded-2xl border border-border/80 bg-background p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{item.subject}</h3><span className="rounded-full border border-border px-2 py-0.5 text-[11px] font-bold uppercase tracking-wide text-muted-foreground">{item.status}</span></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{item.message}</p><p className="mt-3 text-xs text-muted-foreground">{item.name} · {item.email} · consent to reply: {item.consentedToReply ? "yes" : "no"} · received {formatDate(item.createdAt)}</p></div><div className="flex shrink-0 flex-wrap gap-2"><select aria-label={`Update status for contact message ${item.id}`} className="h-9 rounded-lg border border-border bg-card px-2 text-xs" value={item.status} onChange={event => setContactStatus.mutate({ id: item.id, status: event.target.value as typeof contactStatuses[number] })} disabled={pending}>{contactStatuses.map(status => <option key={status} value={status}>{status.replace("_", " ")}</option>)}</select><button type="button" className="inline-flex h-9 items-center gap-1 rounded-lg border border-destructive/30 px-3 text-xs font-bold text-destructive hover:bg-destructive/10 disabled:opacity-50" disabled={pending} onClick={() => { if (window.confirm("Permanently delete this private contact record?")) deleteContact.mutate({ id: item.id }); }}><Trash2 className="size-3.5" />Delete</button></div></div></article>) : <p className="rounded-2xl border border-dashed border-border p-5 text-sm text-muted-foreground">No private contact messages are waiting.</p>}</div>
      </section>

      <section className="rounded-3xl border border-border bg-card p-5 md:p-6" aria-labelledby="waitlist-inbox-title"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Consent to updates</p><h2 id="waitlist-inbox-title" className="mt-1 text-xl font-bold">Waitlist records</h2></div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary">{inbox.data?.waitlist.length ?? 0} private record{inbox.data?.waitlist.length === 1 ? "" : "s"}</span></div>
        <div className="mt-5 space-y-3">{inbox.data?.waitlist.length ? inbox.data.waitlist.map(item => <article key={item.id} className="flex flex-col gap-4 rounded-2xl border border-border/80 bg-background p-4 lg:flex-row lg:items-center lg:justify-between"><div><h3 className="font-semibold">{item.email}</h3><p className="mt-1 text-xs text-muted-foreground">Source: {item.source} · consent recorded {formatDate(item.consentedAt)}</p></div><div className="flex flex-wrap gap-2"><select aria-label={`Update status for waitlist record ${item.id}`} className="h-9 rounded-lg border border-border bg-card px-2 text-xs" value={item.status} onChange={event => setWaitlistStatus.mutate({ id: item.id, status: event.target.value as typeof waitlistStatuses[number] })} disabled={pending}>{waitlistStatuses.map(status => <option key={status} value={status}>{status}</option>)}</select><button type="button" className="inline-flex h-9 items-center gap-1 rounded-lg border border-destructive/30 px-3 text-xs font-bold text-destructive hover:bg-destructive/10 disabled:opacity-50" disabled={pending} onClick={() => { if (window.confirm("Permanently delete this private waitlist record?")) deleteWaitlist.mutate({ id: item.id }); }}><Trash2 className="size-3.5" />Delete</button></div></article>) : <p className="rounded-2xl border border-dashed border-border p-5 text-sm text-muted-foreground">No waitlist records are waiting.</p>}</div>
      </section>
    </>}
    <aside className="flex gap-3 rounded-3xl border border-border bg-card p-5 text-sm leading-6 text-muted-foreground"><MailCheck className="mt-0.5 size-5 shrink-0 text-primary" /><p><strong className="text-foreground">Response checklist:</strong> confirm consent before replying, keep responses in your approved support channel, update the handling state, and delete the record when a verified request or your documented retention rule requires it.</p></aside>
  </section>;
}
