import { InviteDialog, SpaceDialog } from "@/components/SpaceDialogs";
import { WorkspaceErrorState } from "@/components/WorkspaceErrorState";
import { useFinanceWorkspace } from "@/hooks/useFinanceWorkspace";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, Plus, UsersRound } from "lucide-react";
import { useState } from "react";

export default function SpacesPage() {
  const { spaces, activeSpaceId, setActiveSpaceId, isLoading } = useFinanceWorkspace(); const [createOpen, setCreateOpen] = useState(false); const [inviteSpace, setInviteSpace] = useState<{ id: number; name: string } | null>(null);
  const ownedCount = spaces.filter(space => space.role === "owner").length;
  const members = trpc.finance.spaces.members.useQuery({ spaceId: activeSpaceId ?? 0 }, { enabled: !!activeSpaceId });
  if (isLoading) return <div className="workspace-page"><div className="skeleton h-9 w-64" /><div className="skeleton mt-7 h-80" /></div>;
  if (members.isError) return <div className="workspace-page"><WorkspaceErrorState title="We could not load the active Expense Space." message="No membership or invitation has been changed. Check your connection and try this shared view again." onRetry={() => members.refetch()} /></div>;
  return <div className="workspace-page"><header className="workspace-head"><div><p className="workspace-kicker">Keep context clean</p><h1>Expense Spaces</h1><p className="workspace-subtitle">Create up to three owner spaces, and add people only where a shared view is genuinely useful.</p></div>{ownedCount < 3 && <button className="workspace-add" type="button" onClick={() => setCreateOpen(true)}><Plus size={17} /> New space</button>}</header><section className="spaces-grid" aria-label="Available Expense Spaces">{spaces.map(space => <article className={`space-card space-card--${space.color} ${space.id === activeSpaceId ? "is-current" : ""}`} key={space.id}><div className="space-card__top"><span className="space-card__icon" aria-hidden="true">{space.name.slice(0, 1)}</span><span className="space-role">{space.role}</span></div><h2>{space.name}</h2><p>{space.role === "owner" ? "Your private context. Invite people only when the shared view helps." : "A shared context someone has invited you into."}</p><div className="space-card__actions"><button type="button" aria-pressed={space.id === activeSpaceId} onClick={() => setActiveSpaceId(space.id)}>{space.id === activeSpaceId ? <><CheckCircle2 size={15} /> Active</> : <>Use this space <ArrowRight size={15} /></>}</button>{space.role === "owner" && <button type="button" className="space-invite-button" onClick={() => setInviteSpace({ id: space.id, name: space.name })}><UsersRound size={15} /> Invite</button>}</div></article>)}</section>{members.data?.length ? <section className="member-card" aria-labelledby="space-members-heading"><div><p className="workspace-kicker">People in the active space</p><h2 id="space-members-heading">Shared with {members.data.length} member{members.data.length === 1 ? "" : "s"}</h2></div><div className="member-list">{members.data.map(member => <div key={member.id}><span aria-hidden="true">{member.name?.slice(0, 1).toUpperCase() ?? "A"}</span><p><strong>{member.name ?? member.email ?? "Arthra member"}</strong><small>{member.role}</small></p></div>)}</div></section> : null}<p className="spaces-note">Owner spaces: {ownedCount}/3. Shared spaces do not count against this limit.</p><SpaceDialog open={createOpen} onOpenChange={setCreateOpen} />{inviteSpace && <InviteDialog open={!!inviteSpace} onOpenChange={open => !open && setInviteSpace(null)} spaceId={inviteSpace.id} spaceName={inviteSpace.name} />}</div>;
}
