import { TransactionDialog } from "@/components/TransactionDialog";
import { WorkspaceErrorState } from "@/components/WorkspaceErrorState";
import { useFinanceWorkspace } from "@/hooks/useFinanceWorkspace";
import { formatInrFromPaise } from "@shared/finance";
import { trpc } from "@/lib/trpc";
import { FileImage, Loader2, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";

export default function TransactionsPage() {
  const { activeSpace, activeSpaceId, categories, isLoading } = useFinanceWorkspace(); const utils = trpc.useUtils();
  const [dialogOpen, setDialogOpen] = useState(false); const [selected, setSelected] = useState<any>(null); const [query, setQuery] = useState("");
  const transactions = trpc.finance.transactions.list.useQuery({ spaceId: activeSpaceId ?? 0, limit: 250 }, { enabled: !!activeSpaceId });
  const remove = trpc.finance.transactions.delete.useMutation({ onSuccess: () => { utils.finance.transactions.invalidate(); utils.finance.dashboard.invalidate(); utils.finance.analytics.invalidate(); } });
  const rows = useMemo(() => (transactions.data ?? []).filter(item => `${item.description} ${item.categoryName ?? ""}`.toLowerCase().includes(query.toLowerCase())), [transactions.data, query]);
  if (isLoading || !activeSpace) return <WorkspaceSkeleton />;
  if (transactions.isError) return <div className="workspace-page"><WorkspaceErrorState title="We could not retrieve your transactions." message="No entry has been changed. Check your connection and try the active Expense Space again." onRetry={() => transactions.refetch()} /></div>;
  return <div className="workspace-page"><header className="workspace-head"><div><p className="workspace-kicker">{activeSpace.name} space</p><h1>Transactions</h1><p className="workspace-subtitle">Every record is editable, categorised, and ready for a little more context.</p></div><button className="workspace-add" type="button" onClick={() => { setSelected(null); setDialogOpen(true); }}><Plus size={17} /> Add entry</button></header><section className="workspace-card transaction-surface"><div className="transaction-toolbar"><label className="search-field"><Search size={16} aria-hidden="true" /><span className="sr-only">Search transactions</span><input aria-label="Search transactions" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search entries" /></label><span>{rows.length} record{rows.length === 1 ? "" : "s"}</span></div>{transactions.isLoading ? <div className="empty-state"><Loader2 className="animate-spin" /> Loading your entries</div> : rows.length ? <div className="transaction-list transaction-list--page">{rows.map(item => <div className="transaction-row transaction-row--interactive" key={item.id}><span className={`transaction-icon ${item.kind === "income" ? "is-income" : ""}`}>{item.description.slice(0, 1).toUpperCase()}</span><span className="transaction-row__text"><strong>{item.description}</strong><small>{item.categoryName ?? "Uncategorised"} · {new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(item.occurredAt)}{item.isGstApplicable ? " · GST" : ""}</small></span><strong className={item.kind === "income" ? "amount-positive" : "amount-negative"}>{item.kind === "income" ? "+" : "−"}{formatInrFromPaise(item.amountPaise)}</strong><span className="transaction-actions"><button type="button" aria-label={`Edit ${item.description}`} onClick={() => { setSelected(item); setDialogOpen(true); }}><Pencil size={15} /></button><button type="button" aria-label={`Delete ${item.description}`} disabled={remove.isPending} onClick={() => { if (window.confirm(`Delete “${item.description}”?`)) remove.mutate({ transactionId: item.id }); }}><Trash2 size={15} /></button></span></div>)}</div> : <div className="empty-state"><FileImage size={30} /><h2>{query ? "Nothing matched that search." : "No transactions in this space yet."}</h2><p>{query ? "Try a different description or category." : "Begin with one income or expense entry. Receipts, GST context, and notes can follow when you need them."}</p><button className="workspace-add" type="button" onClick={() => setDialogOpen(true)}><Plus size={16} /> Add first entry</button></div>}</section><TransactionDialog open={dialogOpen} onOpenChange={setDialogOpen} spaceId={activeSpace.id} categories={categories} transaction={selected} /></div>;
}
function WorkspaceSkeleton() { return <div className="workspace-page"><div className="skeleton h-9 w-48" /><div className="skeleton mt-7 h-[500px]" /></div>; }
