import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { Check, Copy, Loader2 } from "lucide-react";
import { useState } from "react";

export function SpaceDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const utils = trpc.useUtils(); const [name, setName] = useState(""); const [style, setStyle] = useState("violet");
  const create = trpc.finance.spaces.create.useMutation({ onSuccess: async () => { await utils.finance.bootstrap.invalidate(); setName(""); onOpenChange(false); } });
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="rounded-3xl border-border bg-card"><DialogHeader><DialogTitle>Create an Expense Space</DialogTitle><DialogDescription>Keep a meaningful part of your money life in its own deliberate context.</DialogDescription></DialogHeader><div className="space-y-5 pt-3"><div><Label htmlFor="space-name">Name</Label><Input id="space-name" value={name} onChange={event => setName(event.target.value)} placeholder="e.g. House hunt" className="mt-2" /></div><fieldset><legend className="text-sm font-medium">Accent</legend><div className="space-color-options mt-2">{["violet", "coral", "cyan"].map(color => <button type="button" aria-label={`Use ${color} accent`} aria-pressed={style === color} key={color} className={`space-color space-color--${color} ${style === color ? "is-active" : ""}`} onClick={() => setStyle(color)}>{style === color && <Check size={14} />}</button>)}</div></fieldset><Button type="button" className="w-full rounded-xl py-6" disabled={create.isPending || name.trim().length < 2} onClick={() => create.mutate({ name: name.trim(), color: style, icon: "layers" })}>{create.isPending && <Loader2 className="mr-2 size-4 animate-spin" />}Create private space</Button></div></DialogContent></Dialog>;
}

export function InviteDialog({ open, onOpenChange, spaceId, spaceName }: { open: boolean; onOpenChange: (open: boolean) => void; spaceId: number; spaceName: string }) {
  const [email, setEmail] = useState(""); const [role, setRole] = useState<"editor" | "viewer">("editor"); const [link, setLink] = useState("");
  const invite = trpc.finance.spaces.invite.useMutation({ onSuccess: data => setLink(`${window.location.origin}/join/${data.token}`) });
  async function copy() { await navigator.clipboard.writeText(link); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="rounded-3xl border-border bg-card"><DialogHeader><DialogTitle>Invite to {spaceName}</DialogTitle><DialogDescription>Use an editor role for people who add entries, or viewer for people who only need visibility.</DialogDescription></DialogHeader>{link ? <div className="invite-success"><div className="invite-link">{link}</div><Button type="button" onClick={copy} className="w-full rounded-xl"><Copy className="mr-2 size-4" />Copy shareable link</Button></div> : <div className="space-y-5 pt-3"><div><Label htmlFor="invite-email">Email <span className="text-muted-foreground">optional</span></Label><Input id="invite-email" type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="friend@example.com" className="mt-2" /></div><fieldset><legend className="text-sm font-medium">Permission</legend><div className="segmented-control mt-2" role="group" aria-label="Invite permission"><button type="button" aria-pressed={role === "editor"} className={role === "editor" ? "is-active" : ""} onClick={() => setRole("editor")}>Editor</button><button type="button" aria-pressed={role === "viewer"} className={role === "viewer" ? "is-active" : ""} onClick={() => setRole("viewer")}>Viewer</button></div></fieldset><Button type="button" className="w-full rounded-xl py-6" disabled={invite.isPending} onClick={() => invite.mutate({ spaceId, email: email || undefined, role, expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14) })}>{invite.isPending && <Loader2 className="mr-2 size-4 animate-spin" />}Create invite link</Button></div>}</DialogContent></Dialog>;
}
